### PR TITLE
Use Swift Package Manager to build the project

### PR DESCRIPTION
**Pull request by SimplyDanny**
Xcode is no longer a requirement. This allows Linux/Windows users to build the project, too. An Xcode project can still be generated running `swift package generate-xcodeproj`.

### CODE REVIEW

**Comment by apbendi** [comment]
Only 5 months late to this 😅 

@SimplyDanny would you mind confirming that this change still works with the latest tooling, etc...?

**Comment by SimplyDanny** [comment]
Yes, it still works perfectly fine. I've just updated the tested versions. They were already quite old. 😄

**Comment by SimplyDanny** [comment]
@apbendi: Friendly ping ... 😅

**Comment by apbendi** [comment]
Hi @SimplyDanny, any interesting in PRing an update to the latest language version and tooling? If so, I'll review and merge quickly this time 😇 . No pressure though!

**Comment by SimplyDanny** [comment]
Happy to hear from you! 😄 The versions are still up to date. I re-bumped them about one month ago. Same for https://github.com/apbendi/bitsy-swift/pull/10.

**Comment by apbendi** [comment]
Amazing, merged! Are you still using Bitsy in your teaching? Thank you for your contributions :) Cheers!

**Comment by SimplyDanny** [comment]
Perfect! [SimplyDanny/bitsy-llvm](https://github.com/SimplyDanny/bitsy-llvm) is only a hobby project of mine.

**Pull request merged**
